---
dependencies:
  - name: rabbitmq
    version: 6.2.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.install
  - name: postgresql
    version: 6.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.install
  - name: memcached
    version: 2.9.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: memcached.install
